### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by joshuansu0897**
Adding docker files, and I updated the README

### CODE REVIEW

**Comment by joshuansu0897** [comment]
this was tested on windows 10, docker-desktop with this docker version

```
PS C:\Users\joshu\Documents\Proyectos\migala-form> docker version
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:58:50 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:31 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by AntonioHReyes** [comment]
Hello what's the purpose of add Docker?

**Comment by joshuansu0897** [comment]
Docker is a tool to create containers and that are easy to replicate, a container is an isolated process, an isolated process does not interfere with the rest of your operating system, lib, tool, etc.

So whatever I run on my computer runs on your computer without problems, or servers

on this case I just added the config for the app, but if we need a DB or Cache we can create that container, so, just running `docker-compose up` we can have whole stack on all envs and machines

**Comment by joshuansu0897** [comment]
y... ya me di cuenta de que tienen cosas en español, la costumbre xD 
perdón xD

**Comment by AntonioHReyes** [comment]
Jajajaja va que va compañero me parece buena propuesta jaja aunque tal vez un poco más de complejidad para los que se están integrando jajaja sin embargo este repo quedó obsoleto ya que ya tenemos repo oficial.


Te invito a mandar estos cambios a ese repo :D 

https://github.com/ProyectoMigalaOficial/FormularioPreRegistro

**Pull request closed without merging**
